combine_control_expr = false
condense_wildcard_suffixes = true
edition = "2018"
enum_discrim_align_threshold = 30
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
report_fixme = "Unnumbered"
report_todo = "Unnumbered"
struct_field_align_threshold = 30
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true